version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: order_processor_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_order_data:

networks:
  app_network:
    driver: bridge
