server:
  port: 8080
spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:admin_db}?currentSchema=${DATABASE_SCHEMA:orders}'
    user: ${DATABASE_USR:admin}
    password: ${DATABASE_PWD:admin}
    schemas:
      - ${DATABASE_SCHEMA:orders}
    baseline-on-migrate: true
    locations: classpath:db/migration
beeceptor:
  baseurl: ${BEECEPTOR_BASEURL:https://distribuitioncenters.free.beeceptor.com}
database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:admin_db}
  schema: ${DATABASE_SCHEMA:orders}
  user: ${DATABASE_USR:admin}
  password: ${DATABASE_PWD:admin}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true

beeceptor:
  baseurl: ${BEECEPTOR_BASEURL:https://distribuitioncenters.free.beeceptor.com}