name: Build Project

on:
  push:

env:
  SONAR_TOKEN: squ_7ade39635d0dfa6c12632c925eb3abf7da11d187
  SONAR_HOST_URL: http://ec2-3-16-67-144.us-east-2.compute.amazonaws.com:9000
jobs:
  test:
    name: TEST APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Run Tests
        run: |
          chmod +x ./gradlew
          ./gradlew clean build jacocoTestReport

      - name: Analisar com SonarQube
        run: ./gradlew sonarqube -Dsonar.projectKey=order-processor-service

      - name: Verificar Cobertura de Código
        run: |
          COVERAGE=$(grep -oP '(?<=<counter type="LINE" covered=")\d+' build/reports/jacoco/test/jacocoTestReport.xml | awk '{sum+=$1} END {print sum}')
          TOTAL_LINES=$(grep -oP '(?<=<counter type="LINE" covered=")\d+' build/reports/jacoco/test/jacocoTestReport.xml | wc -l)
          MIN_COVERAGE=80
          echo "-> $COVERAGE%"
          echo "-> $TOTAL_LINES%"
          if [ "$COVERAGE" -lt $((MIN_COVERAGE * TOTAL_LINES / 100)) ]; then
            echo "Cobertura de código insuficiente! Esperado: $MIN_COVERAGE%, obtido: $COVERAGE%"
            exit 1
          fi        

      - name: Verificar Quality Gate do SonarQube
        run: |
          SONAR_STATUS=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=order-processor-service")
          if [[ $(echo "$SONAR_STATUS" | jq -r '.projectStatus.status') != "OK" ]]; then
              echo "Quality Gate falhou no SonarQube!"
              exit 1
          fi
          echo "Quality Gate status: OK"

  build:
    name: BUILD APP
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
